FROM debian:10
LABEL org.opencontainers.image.authors="Open Source Integrators <support@opensourceintegrators.com>"

SHELL ["/bin/bash", "-xo", "pipefail", "-c"]

# Generate locale C.UTF-8
ENV LANG=C.UTF-8
