apiVersion: v1
name: postgresql
version: 2.0
appVersion: 14.0
description: PostgreSQL 14
home: https://www.graymatterlogic.com
icon: https://github.com/ursais.png?width=64
keywords:
- database
- rdbms
- postgresql
sources:
- https://github.com/ursais/docker
maintainers:
- name: Gray Matter Logic
  email: support@graymatterlogic.com
engine: gotpl
