name: Docker
on:
  push:
    branches:
      - master
    tags:
  pull_request:

env:
  APPS: "backup frepple odoo postgresql pyspy"
  OS: "centos debian redhat ubuntu"
  DOCKER_BUILDKIT: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Run tests
        run: |
          OLD_PWD=$(pwd)
          for image in `find . -name Dockerfile`; do
            echo "Building $image..."
            cd $(dirname $image)
            docker build . --file Dockerfile
            echo "Build of $image completed!"
            cd $OLD_PWD
          done

  os:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          OLD_PWD=$(pwd)
          for image in `find $OS -name Dockerfile | sort -r`; do
            echo $image
            DIR=$(dirname $image)
            IMAGE_ID=$(echo $DIR | sed -e 's/^\.\///g' -e 's/\//-/g')
            cd $DIR
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
            [ "$VERSION" == "master" ] && VERSION=latest
            docker build . --file Dockerfile --tag $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
            cd $OLD_PWD
          done

  apps:
    needs: os
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          OLD_PWD=$(pwd)
          for image in `find $APPS -name Dockerfile`; do
            echo $image
            DIR=$(dirname $image)
            IMAGE_ID=$(echo $DIR | sed -e 's/^\.\///g' -e 's/\//-/g')
            cd $DIR
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
            [ "$VERSION" == "master" ] && VERSION=latest
            docker build . --file Dockerfile --tag $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
            cd $OLD_PWD
          done