name: Docker
on:
  push:
    branches:
      - master
    tags:
      - *
  pull_request:

env:
  DOCKER_BUILDKIT: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Run tests
        run: |
          for image in `find . -name Dockerfile`; do
            echo $image
            cd $(dirname $image)
            docker build . --file Dockerfile
          done

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          PWD=$(pwd)
          for image in `find . -name Dockerfile | sort -r`; do
            echo $image
            DIR=$(dirname $image)
            IMAGE_ID=$(echo $DIR | sed -e 's/^\.\///g' -e 's/\//-/g')
            cd $DIR
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
            [ "$VERSION" == "develop" ] && VERSION=latest
            docker build . --file Dockerfile --tag $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
            cd $PWD
          done
