name: Test
on:
  pull_request:

env:
  APPS: "backup frepple odoo postgresql pyspy"
  OS: "centos debian redhat ubuntu"
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Lint Operating Systems"
        run: |
          OLD_PWD=$(pwd)
          for image in `find $OS -name Dockerfile | sort -r`; do
            echo "Linting $image..."
            cd $(dirname $image)
            docker build . --file Dockerfile --check
            cd $OLD_PWD
          done

      - name: "Operating Systems"
        run: |
          OLD_PWD=$(pwd)
          for image in `find $OS -name Dockerfile | sort -r`; do
            echo "Building $image..."
            DIR=$(dirname $image)
            IMAGE_ID=$(echo $DIR | sed -e 's/^\.\///g' -e 's/\//-/g')
            cd $DIR
            docker build . --file Dockerfile --no-cache --tag $IMAGE_ID:latest
            echo "Build of $image completed!"
            cd $OLD_PWD
          done

      - name: "Lint Applications"
        run: |
          OLD_PWD=$(pwd)
          for image in `find $APPS -name Dockerfile | sort -r`; do
            echo "Linting $image..."
            cd $(dirname $image)
            docker build . --file Dockerfile --check
            cd $OLD_PWD
          done

      - name: "Applications"
        run: |
          OLD_PWD=$(pwd)
          for image in `find $APPS -name Dockerfile | sort -r`; do
            echo "Building $image..."
            cd $(dirname $image)
            docker build . --file Dockerfile --no-cache
            ! docker system prune -a -f
            echo "Build of $image completed!"
            cd $OLD_PWD
          done
